name: Publish to npm on PR merge

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Bump version and publish to npm
        run: |
          git config --global user.email "aanikhilsoni@gmail.com"
          git config --global user.name "Nikhil soni"
          git checkout main
          npm version prerelease -m "Auto increment pre-release version to %s [skip ci]" --force
          git push
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
